# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jimmy-landing-page.github.io/landing-page.github.io
title: Jimmy Little
email: thejimmylittle@gmail.com
author: Jimmy
description: Jimmy Little's Landing Page.  This page has links to all the stuff I do around the web.
copyright: 'Copyright &copy; 2016 jimmy little.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/jimmylittle
  - title: facebook
    url: https://www.facebook.com/Jimmy-Little-99821220015
  - title: instagram
    url: https://www.instagram.com/jimmylittle
  - title: linkedin
    url: https://www.linkedin.com/in/jimmylittle
  - title: pinterest
    url: https://www.pinterest.com/jimmylittle
  - title: youtube
    url: https://www.youtube.com/channel/UC5iog8proR-icv1vv48awOQ
    
exclude: ["/_site"]    
